### ISSUE TITLE
100% cpu usage by FiftyOne.Foundation.Mobile.Detection.Feature.Bandwidth.GetIsEnabled

### ISSUE THREAD

**Issue by dmitryRomanchenko** [51Degrees/dotNET-Device-Detection#4] opened 2017-11-28 12:08 UTC
Our app is often locked by 100% cpu usage, Windbg shows a lot of threads similar to these ones https://www.screencast.com/t/ggpsNlrW3JuQ
https://www.screencast.com/t/Z9LUtrIDls
The problem is that FiftyOne.Foundation.Mobile.Detection.Feature.Bandwidth.GetIsEnabled (and other similar methods) uses context.Application which is HttpApplicationState that has a lot of locks. https://referencesource.microsoft.com/#System.Web/httpapplicationstate.cs,38
I think it is better to have a static field somewhere instead of reading that config value from HttpApplicationState on each request.

**Comment by JoshGrew51D** [comment] 2017-11-28 15:25
Hi Dmitry

We are looking into this at the moment and will get back to you shortly. If you have any questions in the meantime drop us a message at support@51degrees,com and we can get in touch with you by Email.

**Comment by Steve51D** [comment] 2017-11-30 13:03
Hi Dmitry

Apologies for the difficulties you've run into and thanks for the detailed information. I think you're spot on with the cause and required fix.
We've made the necessary code changes and will be including this in our next release. (due next week I believe)

I've attached an updated dll to this post so you can try it in advance of the release to make sure it fixes your issue. I wouldn't recommend using this in production though as it hasn't gone through the complete testing process.

Please let us know if you have any further issues.

[FiftyOne.Foundation.zip](https://github.com/51Degrees/dotNET-Device-Detection/files/1517840/FiftyOne.Foundation.zip)

**Comment by dmitryRomanchenko** [comment] 2017-12-01 14:01
Hello, thank you guys for quick response and for the provided solution. We usually have that issue in production under heavy load so we'll wait for the official fix.

**Comment by Steve51D** [comment] 2017-12-07 16:31
Hi Dimitry

Just confirming that the new version is available via nuget.

**Comment by dmitryRomanchenko** [comment] 2017-12-07 16:49
Hello and thank you. We will check it

**Closed as completed** 2017-12-28 12:20 UTC

**Comment by JoshGrew51D** [comment] 2017-12-28 16:49
Hi Dmitry 

Just wanted to check up to see how you are getting on with the patch? 

Can we assume that everything is running smoothly as you have now closed the issue?
